//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.GolestaneShohada.Design.fa {
    
    
    public partial class WarMap {
        
        /// <summary>
        /// UscNaghsheManategheJangi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMS.GolestaneShohada.Controls.UscNaghsheManategheJangi UscNaghsheManategheJangi;
    }
}
