//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NirooYeganVahedAmaliat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NirooYeganVahedAmaliat()
        {
            this.ShahidAmaliats = new HashSet<ShahidAmaliat>();
        }
    
        public int IDNiroo { get; set; }
        public int IDYegan { get; set; }
        public int IDAmaliat { get; set; }
        public int IDVahed { get; set; }
    
        public virtual Niroo Niroo { get; set; }
        public virtual Vahed Vahed { get; set; }
        public virtual Yegan Yegan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShahidAmaliat> ShahidAmaliats { get; set; }
        public virtual Amaliat Amaliat { get; set; }
    }
}
