//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAmaliatNiroo
    {
        public string Kholase { get; set; }
        public string Tozihat { get; set; }
        public Nullable<System.DateTime> TarikhePayan { get; set; }
        public Nullable<System.DateTime> TarikheShoroo { get; set; }
        public string Ramz { get; set; }
        public string Name { get; set; }
        public Nullable<int> IDNiroo { get; set; }
        public Nullable<int> IDYegan { get; set; }
        public Nullable<int> IDVahed { get; set; }
        public int ID { get; set; }
        public string NameNiroo { get; set; }
        public string NameYegan { get; set; }
        public string NameVahed { get; set; }
    }
}
