//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewShahidRabete
    {
        public string Name { get; set; }
        public string Family { get; set; }
        public int IDShahid1 { get; set; }
        public int IDShahid2 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string NameRabete { get; set; }
        public string NoeInSystem { get; set; }
    }
}
