//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewShahidAshena
    {
        public string NameAhena { get; set; }
        public string FamilAshena { get; set; }
        public string Tozihat { get; set; }
        public string Kholase { get; set; }
        public Nullable<int> IDNoeRabete { get; set; }
        public string NameRabete { get; set; }
        public string NameShahid { get; set; }
        public string FamilShahid { get; set; }
        public int ID { get; set; }
    }
}
