//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewShahidAmaliat
    {
        public Nullable<int> IDAmaliat { get; set; }
        public string NameAmaliat { get; set; }
        public Nullable<System.DateTime> TarikheShoroo { get; set; }
        public Nullable<System.DateTime> TarikhePayan { get; set; }
        public string Tozihat { get; set; }
        public string NameRaste { get; set; }
        public string NameNiroo { get; set; }
        public string NameYegan { get; set; }
        public string NameVahed { get; set; }
        public string Name { get; set; }
        public string CodeMeli { get; set; }
        public string Family { get; set; }
        public Nullable<System.DateTime> TarikheTavalod { get; set; }
        public Nullable<System.DateTime> TarikheShahadat { get; set; }
        public string NamePedar { get; set; }
        public string Jensiat { get; set; }
        public string Shoghl { get; set; }
        public byte[] QRCode { get; set; }
        public string NameOstan { get; set; }
        public string NameShahrestan { get; set; }
        public string NameBakhash { get; set; }
        public string VaziateShahid { get; set; }
        public int IDShahid { get; set; }
        public string ShomareShenasname { get; set; }
        public string Ramz { get; set; }
        public Nullable<int> IDYegan { get; set; }
        public Nullable<int> IDNiroo { get; set; }
        public Nullable<int> IDRaste { get; set; }
        public Nullable<int> IDVahed { get; set; }
        public int IDBakhsh { get; set; }
        public int IDOstan { get; set; }
        public int IDShahrestan { get; set; }
        public string NameGhate { get; set; }
        public int GhateID { get; set; }
        public string SangNeveshte { get; set; }
        public Nullable<int> IDNoghteAsar { get; set; }
        public string NameNoghteAsar { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
        public string NameMogheyat { get; set; }
        public string TozihateMogheyat { get; set; }
        public Nullable<int> IDMantaghe { get; set; }
        public string NameMantaghe { get; set; }
        public string TozihateMantaghe { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
        public Nullable<long> ContentLength { get; set; }
        public string ContentType { get; set; }
        public string VirtualAddress { get; set; }
        public string ServerAddress { get; set; }
        public Nullable<bool> ISMonjarBeShahadat { get; set; }
    }
}
