//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAmaliat
    {
        public string NameAmaliat { get; set; }
        public int IDAmaliat { get; set; }
        public string Ramz { get; set; }
        public Nullable<System.DateTime> TarikheShoroo { get; set; }
        public Nullable<System.DateTime> TarikhePayan { get; set; }
        public string Tozihat { get; set; }
        public string Kholase { get; set; }
        public string VirtualAddress { get; set; }
    }
}
