//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(MetaData))]
    [System.ComponentModel.DisplayName("اطلاعات رسیده مخاطبین")]
    public partial class AfzoodaneEtelaat
    {
        private class MetaData
        {
        public int ID { get; set; }
            [Display(Name="توضیحات")]
        public string Tozihat { get; set; }
            [Display(Name="تاریخ ارسال")]
            [UIHint("PersianDate")]
        public Nullable<System.DateTime> TaikheErsal { get; set; }
            [Display(Name="نام ارسال کننده")]
        public string Name { get; set; }
            [Display(Name="نام خانوادگی ارسال کننده")]
        public string Famly { get; set; }
            [Display(Name="تلفن")]
        public string Phone { get; set; }
            [Display(Name="آیا خوانده شده؟")]
        public Nullable<bool> ISRead { get; set; }

        public Nullable<int> IDShahid { get; set; }
    
        public virtual Shahid Shahid { get; set; }
        }
    }
}
