//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(MetaData))]
    [System.ComponentModel.DisplayName("آشنایان")]
    public partial class Ashnayan
    {
        private class MetaData
        {
            public int ID { get; set; }
            [Display(Name="نام")]
            public string Name { get; set; }
            [Display(Name="نام خانوادگی")]
            public string Family { get; set; }
            [Display(Name="توضیحات")]
            public string Tozihat { get; set; }
            [Display(Name="خلاصه")]
            public string Kholase { get; set; }
            public Nullable<int> IDShahid { get; set; }
            public Nullable<int> IDNoeRabete { get; set; }

            public virtual NoeRabete NoeRabete { get; set; }
        }
    }
}
