//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(MetaData))]
    [System.ComponentModel.DisplayName("»Œ‘")]
    public partial class Bakhsh
    {

        private class MetaData
        {
            public int ID { get; set; }
            [Display(Name="‰«„")]
            public string Name { get; set; }
            [Display(Name="›⁄«·")]
            public Nullable<bool> faal { get; set; }
            [Display(AutoGenerateField=false)]
            public Nullable<System.DateTime> dateupdate { get; set; }
            [Display(AutoGenerateField = false)]
            public Nullable<System.Guid> UserID { get; set; }
            public Nullable<int> IDShahrestan { get; set; }

            public virtual Shahrestan Shahrestan { get; set; }

            public virtual ICollection<Shahid> Shahids { get; set; }
        }
    }
}
