//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(MetaData))]
    [System.ComponentModel.DisplayName("منطقه")]
    public partial class MatalebEzafe
    {
        private class MetaData
        {
            public int ID { get; set; }
            public Nullable<int> IDShahid { get; set; }
            public Nullable<int> IDNoeMatlab { get; set; }
            [Display(Name = "توضیحات")]
            public string Tozihat { get; set; }
            [Display(Name = "خلاصه")]
            public string Kholase { get; set; }

            public virtual NoeMatlab NoeMatlab { get; set; }
            public virtual Shahid Shahid { get; set; }
        }
    }
}
