//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    [MetadataType(typeof(MetaData))]
    [System.ComponentModel.DisplayName("نیرو")]
    public partial class Niroo
    {

        private class MetaData
        {

            public int ID { get; set; }
            [Display(Name="نام")]
            public string Name { get; set; }


            public virtual ICollection<Yegan> Yegans { get; set; }

            public virtual ICollection<NirooYeganVahedAmaliat> NirooYeganVahedAmaliats { get; set; }
        }
        public List<Niroo> SelectNiroo()
        {
            using (var myen = Golestan.Helpers.ContextHelper.GetContext)
            {
                return myen.Niroos.ToList();
            }
        }
    }
}
