//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(MetaData))]
    [System.ComponentModel.DisplayName("نیروهای شرکت کننده در عملیات")]

    public partial class NirooYeganVahedAmaliat
    {

        private class MetaData
        {
            public int IDNiroo { get; set; }
            public int IDYegan { get; set; }
            public int IDAmaliat { get; set; }
            public int IDVahed { get; set; }

            public virtual Amaliat Amaliat { get; set; }
            public virtual Niroo Niroo { get; set; }
            public virtual Vahed Vahed { get; set; }
            public virtual Yegan Yegan { get; set; }

            public virtual ICollection<ShahidAmaliat> ShahidAmaliats { get; set; }
        }
    }
}
