//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(MetaData))]
    [System.ComponentModel.DisplayName("نوع رابطه")]
    public partial class NoeRabete
    {

        private class MetaData
        {
            public int ID { get; set; }
            [Display(Name = "نام رابطه")]
            public string Name { get; set; }
            [Display(Name = "نوع در سیستم")]
            public string NoeInSystem { get; set; }


            public virtual ICollection<Ashnayan> Ashnayans { get; set; }

            public virtual ICollection<ShahidRabete> ShahidRabetes { get; set; }
        }
    }
}
