//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    [MetadataType(typeof(MetaData))]
    [System.ComponentModel.DisplayName("نقطه اثر_یادمان")]
    public partial class NoghteAsar
    {
        private class MetaData
        {
            public int ID { get; set; }
            [Display(Name="نام نقطه اثر_یادمان")]
            public string Name { get; set; }
           
            public Nullable<double> X { get; set; }
            public Nullable<double> Y { get; set; }
            [Display(AutoGenerateField=false)]
            public Nullable<System.Guid> AttachID { get; set; }


            public virtual ICollection<Mogheyat> Mogheyats { get; set; }

            public virtual ICollection<Amaliat> Amaliats { get; set; }
        }
        public List<NoghteAsar> SelectNoghteAsarByMogheyat(int IDMogheyat)
        {
            using (var myen = Golestan.Helpers.ContextHelper.GetContext)
            {
                return myen.NoghteAsars.Where(x=>x.Mogheyats.Any(y => y.ID == IDMogheyat)).ToList();
            }
        }
    }
}
