//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(MetaData))]
    [System.ComponentModel.DisplayName("رسته")]


    public partial class Raste
    {
        private class MetaData
        {
            public int ID { get; set; }
            [Display(Name="نام")]
            public string Name { get; set; }
            [Display(Name="توضیحات")]
            public string Tozihat { get; set; }


            public virtual ICollection<ShahidAmaliat> ShahidAmaliats { get; set; }

            public virtual ICollection<Vahed> Vaheds { get; set; }
        }
    }
}
