//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(MetaData))]
    [System.ComponentModel.DisplayName("عملیات های شرکت کرده شهید")]


    public partial class ShahidAmaliat
    {
        private class MetaData
        {
            public int IDAmaliat { get; set; }
            public int IDShahid { get; set; }
            [Display(Name="این عملیات منجر به شهادت شده است؟")]
            public Nullable<bool> ISMonjarBeShahadat { get; set; }
            public Nullable<int> IDRaste { get; set; }
            public Nullable<int> IDVahed { get; set; }
            public Nullable<int> IDYegan { get; set; }
            public Nullable<int> IDNiroo { get; set; }

            public virtual Raste Raste { get; set; }
            public virtual Amaliat Amaliat { get; set; }
            public virtual Shahid Shahid { get; set; }
            public virtual NirooYeganVahedAmaliat NirooYeganVahedAmaliat { get; set; }
        }
    }
}
