//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(MetaData))]
    [System.ComponentModel.DisplayName("واحد")]

    
    public partial class Vahed
    {

        private class MetaData
        {
            public int ID { get; set; }
            [Display(Name="نام")]
            public string Name { get; set; }
            [Display(Name="شرح فعالیت")]
            public string SharheFaliat { get; set; }


            public virtual ICollection<Raste> Rastes { get; set; }

            public virtual ICollection<Yegan> Yegans { get; set; }

            public virtual ICollection<NirooYeganVahedAmaliat> NirooYeganVahedAmaliats { get; set; }
        }
    }
}
