//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(MetaData))]
    [System.ComponentModel.DisplayName("وضعیت")]

    public partial class Vaziat
    {
        private class MetaData
        {
            public int ID { get; set; }
            [Display (Name="نام")]
            public string Name { get; set; }


            public virtual ICollection<Shahid> Shahids { get; set; }
        }
    }
}
