//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golestan.Model
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    [MetadataType(typeof(MetaData))]
    [System.ComponentModel.DisplayName("یگان")]

    
    public partial class Yegan
    {

        private class MetaData
        {
            public int ID { get; set; }
            [Display(Name = "نام")]
            public string Name { get; set; }


            public virtual ICollection<Vahed> Vaheds { get; set; }

            public virtual ICollection<Niroo> Niroos { get; set; }

            public virtual ICollection<NirooYeganVahedAmaliat> NirooYeganVahedAmaliats { get; set; }
        }
        public List<Yegan> SelectYeganByNiroo(int IDNiroo)
        {
            using (var myen = Golestan.Helpers.ContextHelper.GetContext)
            {
                return myen.Yegans.Where(x => x.Niroos.Any(y=>y.ID == IDNiroo)).ToList();
            }
        }
    }
}
